export { default as Category1 } from "./1.json";
export { default as Category2 } from "./2.json";
export { default as Category3 } from "./3.json";
export { default as Category4 } from "./4.json";
export { default as Category5 } from "./5.json";
export { default as Category6 } from "./6.json";
export { default as Category7 } from "./7.json";
export { default as Category8 } from "./8.json";
export { default as Category9 } from "./9.json";
export { default as Category10 } from "./10.json";
export { default as Category11 } from "./11.json";
export { default as Category12 } from "./12.json";
export { default as Category13 } from "./13.json";
export { default as Category14 } from "./14.json";
export { default as Category15 } from "./15.json";
export { default as Category16 } from "./16.json";
export { default as Category17 } from "./17.json";
export { default as Category18 } from "./18.json";
export { default as Category19 } from "./19.json";
// export { default as Category20 } from "./20.json";
// export { default as Category21 } from "./21.json";
// export { default as Category22 } from "./22.json";
// export { default as Category23 } from "./23.json";
// export { default as Category24 } from "./24.json";
// export { default as Category25 } from "./25.json";
